name: Run Scripts Daily

on:
  schedule:
    - cron: '0 0 * * *'     # 5:30 AM IST
    - cron: '30 7 * * *'    # 1:00 PM IST
    - cron: '30 11 * * *'   # 5:00 PM IST
    - cron: '30 15 * * *'   # 9:00 PM IST
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install

    - name: Run all scripts one by one and collect errors
      run: |
        mkdir -p logs
        failed=0
        for file in scripts/add_agenda_at_venue.py; do
          echo "Running $file"
          if ! python "$file" >> logs/$(basename "$file").log 2>&1; then
            echo "$file FAILED" >> logs/failures.txt
            failed=1
          fi
        done
        if [ $failed -eq 1 ]; then
          echo "Some scripts failed. See logs/failures.txt"
          exit 1
        fi

    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: script-logs
        path: logs/
