name: Run Scripts Daily

on:
  schedule:
    - cron: '0 0 * * *'     # 5:30 AM IST
    - cron: '30 7 * * *'    # 1:00 PM IST
    - cron: '30 11 * * *'   # 5:00 PM IST
    - cron: '30 15 * * *'   # 9:00 PM IST
  workflow_dispatch:

jobs:
  run-test2-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install

      - name: Run test2_tempmail_py.py and save logs
        run: |
          mkdir -p logs
          if ! python scripts/test2_tempmail_py.py >> logs/test2_tempmail_py.log 2>&1; then
            echo "scripts/test2_tempmail_py.py FAILED" >> logs/failures.txt
            exit 1
          fi

      - name: Upload logs and screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: logs/
